spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;
    username: sa
    password:

jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=